### ISSUE TITLE
Not able to install Roomify / RfA and error

### ISSUE THREAD

**Issue by VillaCare** [Roomify/RfA#405]
Due to a trojan virus the web page build was destroyed and was not able to restore the back up make. 

Now try to set up a new site but receive following error message after upload of files and DB:

Fatal error: Declaration of RulesConditionalEmptyUI::form(&$form, &$form_state, $options = Array) must be compatible with RulesContainerPluginUI::form(&$form, &$form_state, $options = Array, $iterator = NULL) in /homepages/40/d568653886/htdocs/clickandbuilds/roomify-accommodations/profiles/roomify/modules/contrib/rules_conditional/includes/rules_conditional.ui.inc on line 39
Uncaught exception thrown in shutdown function.

FacesExtendableException: There is no method process for this instance of the class RulesAction. in FacesExtendable->__call() (line 133 of /homepages/40/d568653886/htdocs/clickandbuilds/roomify-accommodations/profiles/roomify/modules/contrib/rules/includes/faces.inc).

## Expected Behavior

Roomify installation
## Current Behavior

The following error appears: 

Fatal error: Declaration of RulesConditionalEmptyUI::form(&$form, &$form_state, $options = Array) must be compatible with RulesContainerPluginUI::form(&$form, &$form_state, $options = Array, $iterator = NULL) in /homepages/40/d568653886/htdocs/clickandbuilds/roomify-accommodations/profiles/roomify/modules/contrib/rules_conditional/includes/rules_conditional.ui.inc on line 39
Uncaught exception thrown in shutdown function.

FacesExtendableException: There is no method process for this instance of the class RulesAction. in FacesExtendable->__call() (line 133 of /homepages/40/d568653886/htdocs/clickandbuilds/roomify-accommodations/profiles/roomify/modules/contrib/rules/includes/faces.inc).
## Steps to Reproduce from a clean installation of the latest release

1.new install of Roomify onto a 1&1 hosting server

<img width="1054" alt="Screenshot 2019-03-26 at 13 02 20" src="https://user-images.githubusercontent.com/25827314/54995628-6c906780-4fc7-11e9-913c-f5d33f1516ad.png">

2.
3.
4.

## Context (Environment)

1st lost actif web site, now need to set up new one from scratch

Safari / IOS

Now sure if it is a program issue or 1&1 issue, contacted them several times but say all is fine from their side.

**Comment by VillaCare** [comment]
Made a new install, on settings I needed to change and than I could start install but have now this issue: 
<img width="839" alt="Screenshot 2019-03-26 at 21 22 17" src="https://user-images.githubusercontent.com/25827314/55030847-7dfc6280-500d-11e9-85ed-c12ce4224064.png">
Pls advise on what to do.

**Comment by acrollet** [comment]
@VillaCare that looks like a file permissions issue, see https://www.drupal.org/node/244924 for more background.

**Comment by VillaCare** [comment]
Thanks, but with the following settings 




I have this:




What settings should it have as the settings.php is the only which should be changed,

Rgds,




Ferdinand van Reijsen
VillaCare
HTTP://www.villacare.eu

**Comment by acrollet** [comment]
@VillaCare it looks like your issue is related to this: https://www.drupal.org/project/rules/issues/2954844

It should be resolved with the next release of RfA. In the meantime, you could try either:

* Using PHP 7.1, or
* Manually updating Drupal core and Rules to the latest releases.

**Comment by VillaCare** [comment]
Thanks again, updated Drupal and Rules but without result, same issue remains. When would a new release be rolled out? Should rules conditional also being updated?

Rgds,






Ferdinand van Reijsen
VillaCare
HTTP://www.villacare.eu
